[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#FFFDF2"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#CBE5EF"

# Color used for almost all text.
# textColor = "fff"
textColor = "#000000"

# Font size
baseFontSize=18

[client]
toolbarMode = "minimal"

